name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: detect_leaks=1
      UBSAN_OPTIONS: print_stacktrace=1,halt_on_error=1
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Configure
        run: xmake config -y -m debug
      - name: Test
        run: xmake test -y
